
name: mdview
version: '1.4.0'
summary: View markdown files in a browser from the command line.
description: |
  Command line tool to view a markdown file in your default web browser.
  Type `mdview --help` for options. https://github.com/mapitman/mdview
grade: stable
confinement: strict
base: core18
apps:
    mdview:
      command: bin/mdview
      plugs: [home,unity7]
      environment:
        HOME: /home/$USER
parts:
  mdview:
    plugin: go
    source: .
    # source-type: git
    build-packages:
      - gcc
      - gcc-multilib
      - libblkid-dev
