
  name: mdview
  version: '1.0'
  summary: View markdown files in a browser from the command line.
  description: |
    Command line tool to view a markdown file in your default web browser.
    Type `mdview --help` for options. https://github.com/mapitman/mdview
  grade: candidate
  confinement: strict

  apps:
      mdview:
        command: mdview
        plugs: [home]
  parts:
    mdview:
      build-packages: [golang]
      plugin: go

  
